run:
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa9_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 > live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa10_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa11_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa12_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa13_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa14_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa15_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pa1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pa16_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb9_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb10_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb11_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb12_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb13_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb14_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb15_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rb1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rb16_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh9_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh10_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh11_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh12_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh13_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh14_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh15_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/rh1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/rh16_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf9_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf10_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf11_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf12_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf13_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf14_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf15_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sf1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sf16_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs9_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs10_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs11_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs12_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs13_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs14_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs15_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/bs1_25fps.yuv --dist_path /datasets/live-vqa/yuv/dis/bs16_25fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh9_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh10_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh11_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh12_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh13_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/sh1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/sh14_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc9_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc10_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc11_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc12_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc13_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc14_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc15_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/mc1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/mc16_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr9_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr10_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr11_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr12_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr13_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr14_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr15_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log
	python3 demo_score.py --ref_path /datasets/live-vqa/yuv/ref/pr1_50fps.yuv --dist_path /datasets/live-vqa/yuv/dis/pr16_50fps.yuv --width 768 --height 432 --ref_fps 25 --dist_fps 25 >> live-vqa.log